from . import elastic_connection
from . import elastic_config
from . import elastic_catalog
from . import elastic_export_log
from . import elastic_import_log
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import elastic_customer_xref
from . import elastic_order_staging
