# -*- coding: utf-8 -*-
import base64
import csv
from io import StringIO

from odoo import _, models, fields, api
from odoo.exceptions import UserError


class ElasticCatalog(models.Model):
    _name = 'elastic.catalog'
    _description = 'Elastic Catalog'
    _order = 'name'

    name = fields.Char(string='Catalog Name', required=True)
    code = fields.Char(string='Catalog Code', required=True, help='Unique code for this catalog')
    description = fields.Text(string='Description')
    active = fields.Boolean(string='Active', default=True)

    catalog_permission_group = fields.Char(
        string='Permission Group',
        default='DEFAULT',
        help='CatalogPermissionGroup value sent to Elastic.'
    )
    catalog_type = fields.Char(
        string='Catalog Type',
        default='nonblocking',
        help='CatalogType value sent to Elastic.'
    )
    catalog_position = fields.Integer(
        string='Catalog Position',
        default=0,
        help='CatalogPosition value sent to Elastic. Falls back to the Odoo ID when left as 0.'
    )
    catalog_mapping_position = fields.Integer(
        string='Catalog Mapping Position',
        default=1,
        help='CatalogPosition value sent in catalog_mapping.csv rows for this catalog.'
    )
    start_date = fields.Date(string='Start Date')
    end_date = fields.Date(string='End Date')
    review_flag = fields.Selection(
        [('N', 'No'), ('Y', 'Yes')],
        string='Review Flag',
        default='N',
        required=True,
    )
    first_ship_date = fields.Date(string='First Ship Date')
    last_ship_date = fields.Date(string='Last Ship Date')
    last_cancel_date = fields.Date(string='Last Cancel Date')
    default_cancel_days = fields.Integer(string='Default Cancel Days', default=30)
    season_code = fields.Char(string='Season Code', default='ALL')
    ship_min_days = fields.Integer(string='Ship Min Days')
    ship_default_days = fields.Integer(string='Ship Default Days')
    ship_max_days = fields.Integer(string='Ship Max Days')
    max_cancel_days = fields.Integer(string='Max Cancel Days')
    min_cancel_days = fields.Integer(string='Min Cancel Days')
    warehouse = fields.Char(string='Warehouse')
    ship_date_1 = fields.Date(string='Ship Date 1')
    ship_date_2 = fields.Date(string='Ship Date 2')
    ship_date_3 = fields.Date(string='Ship Date 3')
    ship_date_4 = fields.Date(string='Ship Date 4')
    ship_date_5 = fields.Date(string='Ship Date 5')
    brand = fields.Char(string='Brand')
    catalog_classification = fields.Char(string='Catalog Classification', default='ATS')
    price_group = fields.Char(string='Price Group')
    mapping_source = fields.Selection(
        [('generated', 'Generated by Odoo'), ('uploaded', 'Uploaded File')],
        string='Mapping Source',
        default='generated',
        required=True,
    )
    mapping_sort_method = fields.Selection(
        [
            ('style_color', 'Style, Color'),
            ('product_class_style_color', 'Product Class, Style, Color'),
        ],
        string='Generated Mapping Sort',
        default='style_color',
        required=True,
    )
    mapping_upload = fields.Binary(string='Pre-Sorted Mapping File')
    mapping_upload_filename = fields.Char(string='Mapping Filename')
    mapping_line_ids = fields.One2many(
        'elastic.catalog.mapping.line',
        'catalog_id',
        string='Catalog Mapping Lines',
        copy=False,
    )
    mapping_line_count = fields.Integer(
        string='Mapping Lines',
        compute='_compute_mapping_line_count',
        store=True,
    )

    product_ids = fields.Many2many(
        'product.template',
        'product_template_elastic_catalog_rel',
        'catalog_id',
        'product_id',
        string='Product Templates'
    )
    variant_ids = fields.Many2many(
        'product.product',
        'product_product_elastic_catalog_rel',
        'catalog_id',
        'product_id',
        string='Product Variants'
    )
    partner_ids = fields.Many2many(
        'res.partner',
        'partner_elastic_catalog_rel',
        'catalog_id',
        'partner_id',
        string='Customers'
    )

    product_count = fields.Integer(string='Product Template Count', compute='_compute_product_count', store=True)
    variant_count = fields.Integer(string='Variant Count', compute='_compute_variant_count', store=True)
    partner_count = fields.Integer(string='Customer Count', compute='_compute_partner_count', store=True)

    _sql_constraints = [
        ('code_unique', 'UNIQUE(code)', 'Catalog code must be unique!')
    ]

    @api.depends('product_ids')
    def _compute_product_count(self):
        for record in self:
            record.product_count = len(record.product_ids)

    @api.depends('variant_ids')
    def _compute_variant_count(self):
        for record in self:
            record.variant_count = len(record.variant_ids)

    @api.depends('partner_ids')
    def _compute_partner_count(self):
        for record in self:
            record.partner_count = len(record.partner_ids)

    @api.depends('mapping_line_ids')
    def _compute_mapping_line_count(self):
        for record in self:
            record.mapping_line_count = len(record.mapping_line_ids)

    def _get_exportable_mapping_products(self):
        self.ensure_one()
        products = self.product_ids.mapped('product_variant_ids') | self.variant_ids
        return products.filtered(
            lambda product: product.active
            and product.sale_ok
            and product._get_elastic_item_number()
        )

    def _get_mapping_color_code(self, product):
        self.ensure_one()
        for attr_value in product.product_template_attribute_value_ids:
            if (attr_value.attribute_id.name or '').strip().lower() not in {
                'color',
                'colour',
                'frame color',
                'product color',
            }:
                continue

            value = attr_value.product_attribute_value_id
            elastic_color = self.env['elastic.color'].search([
                '|',
                ('odoo_attribute_value_id', '=', value.id),
                ('odoo_attribute_value_ids', 'in', value.id),
                ('active', '=', True),
            ], limit=1)
            if elastic_color:
                return elastic_color.code

            code = value.name or ''
            return code[:3].upper() if len(code) > 5 else code
        return ''

    def _get_mapping_sort_key(self, product, color_code):
        self.ensure_one()
        item_number = product._get_elastic_item_number()
        product_class = product.product_tmpl_id.categ_id.complete_name or product.product_tmpl_id.categ_id.name or ''
        if self.mapping_sort_method == 'product_class_style_color':
            return (product_class.upper(), item_number.upper(), (color_code or '').upper())
        return (item_number.upper(), (color_code or '').upper())

    def _prepare_generated_mapping_rows(self):
        self.ensure_one()
        rows = []
        for product in self._get_exportable_mapping_products():
            color_code = self._get_mapping_color_code(product)
            rows.append({
                'product_id': product.id,
                'item_number': product._get_elastic_item_number(),
                'color_code': color_code,
                'product_class': product.product_tmpl_id.categ_id.complete_name or product.product_tmpl_id.categ_id.name or '',
                'sort_key': self._get_mapping_sort_key(product, color_code),
            })

        rows.sort(key=lambda row: row['sort_key'])
        return rows

    def action_generate_mapping_lines(self):
        for catalog in self:
            rows = catalog._prepare_generated_mapping_rows()
            catalog.mapping_line_ids.unlink()
            catalog.write({
                'mapping_source': 'generated',
                'mapping_line_ids': [
                    (0, 0, {
                        'sequence': index,
                        'catalog_position': catalog.catalog_mapping_position or 1,
                        'product_id': row['product_id'],
                        'item_number': row['item_number'],
                        'color_code': row['color_code'],
                        'product_class': row['product_class'],
                    })
                    for index, row in enumerate(rows, start=1)
                ],
            })
        row_count = sum(len(catalog.mapping_line_ids) for catalog in self)
        return self._mapping_notification(
            _('Catalog mappings generated: %s row(s).') % row_count,
            reload_view=True,
        )

    def action_import_mapping_upload(self):
        for catalog in self:
            if not catalog.mapping_upload:
                raise UserError(_('Upload a catalog_mapping.csv file before loading mapping lines.'))

            content = base64.b64decode(catalog.mapping_upload).decode('utf-8-sig')
            reader = csv.DictReader(StringIO(content))
            required_headers = {'CatalogKey', 'CatalogPosition', 'ItemNumber', 'ColorCode'}
            if not reader.fieldnames or not required_headers.issubset(set(reader.fieldnames)):
                raise UserError(_('The uploaded file must include CatalogKey, CatalogPosition, ItemNumber, and ColorCode.'))

            lines = []
            for index, row in enumerate(reader, start=1):
                if (row.get('CatalogKey') or '').strip() != catalog.code:
                    continue
                item_number = (row.get('ItemNumber') or '').strip()
                if not item_number:
                    continue
                try:
                    catalog_position = int(row.get('CatalogPosition') or catalog.catalog_mapping_position or 1)
                except ValueError:
                    catalog_position = catalog.catalog_mapping_position or 1

                lines.append((0, 0, {
                    'sequence': index,
                    'catalog_position': catalog_position,
                    'item_number': item_number,
                    'color_code': (row.get('ColorCode') or '').strip(),
                }))

            if not lines:
                raise UserError(_('No mapping rows were found for catalog code %s.') % catalog.code)

            catalog.mapping_line_ids.unlink()
            catalog.write({
                'mapping_source': 'uploaded',
                'mapping_line_ids': lines,
            })
        row_count = sum(len(catalog.mapping_line_ids) for catalog in self)
        return self._mapping_notification(
            _('Uploaded catalog mapping loaded: %s row(s).') % row_count,
            reload_view=True,
        )

    @api.model
    def generate_active_catalog_mapping_lines(self):
        catalogs = self.search([('active', '=', True), ('mapping_source', '=', 'generated')])
        catalogs.action_generate_mapping_lines()
        return len(catalogs)

    def _mapping_notification(self, message, notification_type='success', reload_view=False):
        action = {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Catalog Mapping'),
                'message': message,
                'type': notification_type,
                'sticky': False,
            }
        }
        if reload_view:
            action['params']['next'] = {'type': 'ir.actions.client', 'tag': 'reload'}
        return action


class ElasticCatalogMappingLine(models.Model):
    _name = 'elastic.catalog.mapping.line'
    _description = 'Elastic Catalog Mapping Line'
    _order = 'catalog_id, sequence, id'

    catalog_id = fields.Many2one(
        'elastic.catalog',
        string='Catalog',
        required=True,
        ondelete='cascade',
        index=True,
    )
    sequence = fields.Integer(default=10, index=True)
    catalog_position = fields.Integer(string='Catalog Position', default=1)
    product_id = fields.Many2one('product.product', string='Product Variant', ondelete='set null')
    item_number = fields.Char(string='ItemNumber', required=True, index=True)
    color_code = fields.Char(string='ColorCode')
    product_class = fields.Char(string='Product Class')
    active = fields.Boolean(related='catalog_id.active', store=True)

    _sql_constraints = [
        (
            'catalog_item_color_unique',
            'UNIQUE(catalog_id, item_number, color_code)',
            'A catalog mapping line with this ItemNumber and ColorCode already exists for this catalog.'
        ),
    ]
